# Generated by Django 4.0.6 on 2022-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Lead', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=40)),
                ('Services', models.CharField(max_length=40)),
                ('Domain', models.CharField(max_length=40)),
                ('Channels', models.CharField(max_length=40)),
                ('Stage', models.CharField(max_length=40)),
                ('Status', models.CharField(max_length=40)),
                ('Amount', models.CharField(max_length=40)),
                ('Sale_Representative', models.CharField(max_length=40)),
                ('Created_at', models.CharField(max_length=40)),
                ('Signed_at', models.CharField(max_length=40)),
                ('Closed_at', models.CharField(max_length=40)),
            ],
        ),
    ]
