# Generated by Django 4.0.6 on 2022-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_sale_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Lead',
            field=models.CharField(max_length=40),
        ),
    ]
