# Generated by Django 4.0.6 on 2022-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_id_alter_employee_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Sale_Representative',
            field=models.CharField(max_length=100),
        ),
    ]
